name: My First GitHub action

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: First Message
        run: echo "Hello from the Github Actions!"

      - name: Second Message
        run: echo "I am learning CI/CD"

      - name: Third Message
        run: echo "I am going to use this for my data engineering project"

  new_job:
    runs-on: ubuntu-latest

    steps:
      - name: First Message of new job
        run: echo "The task of new job is completed"

  pushing_files_actions:
    runs-on: ubuntu-latest

    steps:
      - name: Pushing files
        uses: actions/checkout@v4

      - name: list all the files
        run: ls -la

  python_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List all files
        run: ls -la

      - name: Python environment setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run .py files
        run: python main.py